//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(lavaWave)

const palette_color_t lavaWave_palettes[4] = {
	RGB8(155, 188, 15), RGB8(139, 172, 15), RGB8(48, 98, 48), RGB8(192, 0, 124)
};

const uint8_t lavaWave_tiles[32] = {
	0x00,0x0e,0x0e,0xf1,0xff,0x00,0xbe,0x41,0xf7,0x08,0xff,0x00,0xed,0x12,0xbf,0x40,0xfb,0x04,0xfe,0x01,0xaf,0x50,0xff,0x00,0x7d,0x82,0xef,0x10,0xfd,0x02,0xbf,0x40
};

const metasprite_t lavaWave_metasprite0[] = {
	METASPR_ITEM(-8, -80, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_ITEM(0, 8, 0, 0), METASPR_TERM
};

const metasprite_t* const lavaWave_metasprites[1] = {
	lavaWave_metasprite0
};

#include "MetaSpriteInfo.h"
const struct MetaSpriteInfo lavaWave = {
	160, //width
	16, //height
	2, //num tiles
	lavaWave_tiles, //tiles
	1, //num palettes
	lavaWave_palettes, //CGB palette
	1, //num sprites
	lavaWave_metasprites, //metasprites
};
